name: Auto Deploy to PROD

on:
  push:
    branches:
      - main # Пайплайн сработает при пуше в ветку main

jobs:
  deploy:
    runs-on: self-hosted # Запуск на вашем локальном ПК, а не на серверах GitHub
    
    steps:
      - name: Pull latest changes in PROD
        run: |
          git pull origin main